### ISSUE TITLE
Flickering Fog and graphical issues with Alex's Caves

### ISSUE THREAD

**Issue by HollyBlocky** [shizotoaster/foglooksmodernnow#1] opened 2023-10-22 04:37 UTC
I know the Modern Fabric version of the mod had issues with Sodium. Likewise, this mod also suffers from incompatibility with Embeddium and Rubidium, the Forge ports of Sodium. The fog will flicker when you move around, and isn't optimal for gameplay.

**Comment by shizotoaster** [comment] 2023-10-23 14:09
Wasn't able to reproduce that behavior on MC 1.20.1 Forge 47.1.3 and Embeddium 0.2.2. What mc, forge and embeddium version are you on?

**Comment by HollyBlocky** [comment] 2023-10-23 19:44
MC 1.20.1 Forge 47.2.0 and Embeddium 0.2.2. Though, I'm not for certain it's Embeddium since I've got a lot of mods running (and it's on multiplayer). (Oculus, Super Fancy Clouds Rearchitected, modernfix--though I already tested if this was the cause and it doesnt seem to be, memory leak fix, to name a few) I'm gonna test a few more sessions to try and find out which mod is causing fog to flicker

**Comment by HollyBlocky** [comment] 2023-10-23 20:16
While I do that testing, here's my log and debug:
[debug.log](https://github.com/shizotoaster/foglooksmodernnow/files/13078810/debug.log)
[latest.log](https://github.com/shizotoaster/foglooksmodernnow/files/13078811/latest.log)

**Comment by HollyBlocky** [comment] 2023-10-23 20:26
I've narrowed it down to it either being an issue with the Forge version or with "Alex's Caves" it looks like

**Comment by HollyBlocky** [comment] 2023-10-23 20:34
Alright, I can say with 100% certainty the issue is with Alex's Caves

**Comment by shizotoaster** [comment] 2023-10-24 02:31
Alex' caves is known to break mods that modify game fog code. Might be a problem as it completely overwrites some methods for "compatibility reasons"

**Comment by GrandeMalum** [comment] 2023-11-16 16:23
Oh... that's sad. Looks like this issue can't be fixed any time soon, right?

**Comment by shizotoaster** [comment] 2023-11-16 22:00
Fixed in latest update (1.1.0), thanks for the report

**Closed as completed by shizotoaster** 2023-11-16 22:00 UTC

**Comment by GrandeMalum** [comment] 2023-11-20 15:31
You are awesome. Thank you, dear developer.
